<?php

namespace App\Observers;

use App\Http\Middleware\SeoRedirectMiddleware;
use App\Jobs\Seo\PingIndexNowJob;
use App\Jobs\Seo\RegenerateSitemapJob;
use App\Models\Blog;
use App\Models\Category;
use App\Models\Page;
use App\Models\Product;
use App\Models\SeoRedirect;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Schema;
use Throwable;

/**
 * Generic slug-change watcher: when a Product/Category/Page/Blog slug changes,
 * automatically create a 301 from the old URL to the new URL so external
 * inbound links don't break.
 *
 * Wired through SeoServiceProvider — one instance is attached to each model
 * class. The model determines the URL pattern via {@see urlForOldSlug()}.
 */
class SeoEntitySlugObserver
{
    public function updating(Model $entity): void
    {
        if (!$entity->isDirty('slug')) {
            return;
        }

        $oldSlug = $entity->getOriginal('slug');
        $newSlug = $entity->slug;

        if (!$oldSlug || !$newSlug || $oldSlug === $newSlug) {
            return;
        }

        if (!Schema::hasTable('seo_redirects')) {
            return;
        }

        $source = $this->urlForSlug($entity, $oldSlug);
        $target = $this->urlForSlug($entity, $newSlug);

        if (!$source || !$target || $source === $target) {
            return;
        }

        try {
            SeoRedirect::updateOrCreate(
                ['source_url' => $source],
                [
                    'target_url'  => $target,
                    'status_code' => 301,
                    'is_active'   => true,
                    'notes'       => 'Auto-created: ' . class_basename($entity) . '#' . $entity->getKey() . ' slug change',
                ]
            );

            Cache::forget(SeoRedirectMiddleware::CACHE_KEY);
        } catch (Throwable $e) {
            logger()->warning('SEO auto-redirect failed', [
                'model' => get_class($entity),
                'id'    => $entity->getKey(),
                'error' => $e->getMessage(),
            ]);
        }
    }

    protected function urlForSlug(Model $entity, string $slug): ?string
    {
        if ($entity instanceof Product) {
            return '/product/' . $slug;
        }
        if ($entity instanceof Category) {
            return '/category/' . $slug;
        }
        if ($entity instanceof Page) {
            return '/' . $slug;
        }
        if ($entity instanceof Blog) {
            return '/blog/' . $slug;
        }
        return null;
    }

    /**
     * After-save hook: bust sitemap cache + optionally ping IndexNow.
     * Runs for every save, but only fires the IndexNow ping when the entity
     * is in a publish-ready state.
     */
    public function saved(Model $entity): void
    {
        $this->bustSitemapCaches();

        if (!$this->isPublished($entity)) {
            return;
        }

        $url = $this->absoluteUrlFor($entity);
        if (!$url) {
            return;
        }

        if ((int) get_setting('seo_auto_indexnow', 0)) {
            $this->tryDispatch(fn() => PingIndexNowJob::dispatch([$url]));
        }

        if ((int) get_setting('seo_auto_cloudflare_purge', 0)) {
            $this->tryDispatch(fn() => \App\Jobs\Seo\PurgeCloudflareUrlsJob::dispatch([$url]));
        }

        // Opt-in real-time sitemap refresh, debounced ~5 min so a burst of saves
        // triggers a single regeneration. Default off — the scheduler handles it.
        if ((int) get_setting('seo_auto_sitemap_realtime', 0) === 1
            && Cache::add('seo:sitemap:regen:debounce', 1, now()->addMinutes(5))) {
            $this->tryDispatch(fn() => RegenerateSitemapJob::dispatch());
        }
    }

    protected function tryDispatch(callable $dispatcher): void
    {
        try {
            $dispatcher();
        } catch (Throwable $e) {
            logger()->warning('SEO save-hook dispatch failed', ['error' => $e->getMessage()]);
        }
    }

    /**
     * Bust any cached sitemap/scoring keys so the next request rebuilds them.
     * Cheap: only cache keys, not raw files. The on-disk sitemap.xml is
     * regenerated by the daily scheduler in Phase 6.
     */
    protected function bustSitemapCaches(): void
    {
        foreach ([
            'seo:sitemap:urls',
            'seo:sitemap:smart',
            'seo:sitemap:lastmod',
            'seo:meta-resolver',
        ] as $key) {
            try {
                Cache::forget($key);
            } catch (Throwable $e) {
                // Cache backend issues are non-fatal here.
            }
        }
    }

    protected function isPublished(Model $entity): bool
    {
        if ($entity instanceof Product) {
            return (int) ($entity->published ?? 0) === 1 && (int) ($entity->approved ?? 1) === 1;
        }
        if ($entity instanceof Blog) {
            return (int) ($entity->status ?? 0) === 1;
        }
        // Pages and Categories are always treated as live once they exist.
        return true;
    }

    protected function absoluteUrlFor(Model $entity): ?string
    {
        $slug = $entity->slug ?? null;
        if (!$slug) {
            return null;
        }
        $base = rtrim(url('/'), '/');

        if ($entity instanceof Product)  return $base . '/product/'  . $slug;
        if ($entity instanceof Category) return $base . '/category/' . $slug;
        if ($entity instanceof Page)     return $base . '/'          . $slug;
        if ($entity instanceof Blog)     return $base . '/blog/'     . $slug;

        return null;
    }
}
