<?php

namespace App\Http\Middleware\PerformanceOptimizer;

use Closure;
use Illuminate\Http\Request;

/**
 * The Vitals endpoint is called by `navigator.sendBeacon` from cached HTML
 * pages, where the embedded `_token` may be stale or missing. We don't trust
 * the body for any state mutation — we only INSERT a metric row. So full CSRF
 * is overkill and breaks legitimate beacons.
 *
 * This middleware:
 *  - Verifies the request was generated by a real browser (has User-Agent and Origin/Referer matching app URL).
 *  - Skips Laravel's CSRF middleware via VerifyCsrfToken::$except (add manually) OR bypasses inline.
 *  - Caps body size at 2 KB.
 */
class VitalsCollectMiddleware
{
    public function handle(Request $request, Closure $next)
    {
        if ((int) get_setting('perf_vitals_collect_status', 0) !== 1) {
            return response()->json(['success' => false, 'reason' => 'disabled'], 200);
        }

        // Reject obvious bots/curl — Vitals must come from a browser.
        $ua = (string) $request->userAgent();
        if ($ua === '' || strlen($ua) > 500) {
            return response()->json(['success' => false, 'reason' => 'invalid_ua'], 400);
        }

        // Same-origin check (Origin or Referer must start with app URL)
        $appHost = parse_url(config('app.url'), PHP_URL_HOST);
        $origin  = (string) ($request->headers->get('Origin') ?: $request->headers->get('Referer') ?: '');
        if ($appHost && $origin && !str_contains($origin, $appHost)) {
            return response()->json(['success' => false, 'reason' => 'cross_origin'], 403);
        }

        // Cap body size
        if (strlen((string) $request->getContent()) > 2048) {
            return response()->json(['success' => false, 'reason' => 'body_too_large'], 413);
        }

        return $next($request);
    }
}
